### ISSUE TITLE
Add `Paragraph` and `MenuFlex` to mark-one

### ISSUE THREAD

**Issue by Urjikoo** [seas-computing/mark-one#171]
We have created a new custom styled component `Paragraph` to have page titles more prominent (ie replacing `h2` tag), when apply.seas was built. However as future projects, such as Makerspace, have similar features, we should add both `Paragraph` and `MenuFlex` to mark-one to make it more standardize it.

---

- [ ] Test
- [ ] Docs

**Comment by jonseitz** [comment]
Closed by #174
