### ISSUE TITLE
Toast Notification Wrapper Component

### ISSUE THREAD

**Issue by natalynyu** [seas-computing/mark-one#197]
This component will wrap the `ToastNotification` component(s) such that they are aligned vertically at the top right of the browser.  We will determine in the future whether we will use a scroll bar for notifications that don't fit on the page or add a button to show additional notifications.

**Comment by Vittorio2015** [comment]
I have captured here our feedback, such as

- Thicker border lines to make the colors of notification types (warning, info and success) more evident
- Scroll bar for the notifications container, which also indicates for the presence of notifications that don’t fit in the display
- Once I did that, I thought of defining the notifications container more evidently, also by adding to the top a notice with the total notifications to review (“10 notifications to review”)
- I don’t believe drop shadows are longer needed

As you know, this is just a way to commit to a visual what we discussed, not a final design; I don’t want to compromise Natalyn’s progress.
<img width="1424" alt="Screenshot 2024-09-20" src="https://github.com/user-attachments/assets/1b898826-b90f-41a9-a94d-df94acb123c3">
